trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'build'
    jobs:
    - job: 'buildJob'
      steps:
        - task: 'UseDotNet@2'
          inputs:
            version: '3.1.x'
            packageType: runtime
        - task: 'DotNetCoreCLI@2'
          inputs:
            command: 'build'
            projects: '**/RevatureP1.sln'
            arguments: '--configuration $(buildConfiguration)'
#    - job: 'testJob'
#      dependsOn: 'buildJob'
#      steps:
#        - task: 'DotNetCoreCLI@2'
#          inputs:
#            command: 'test'
#            projects: 'project1\WebStoreApp\WebStoreApp.Testing\WebStoreApp.Testing.csproj'
    - job: 'publishJob'
#      dependsOn: 'testJob'
      dependsOn: 'buildJob'
      steps:
        - task: 'DotNetCoreCLI@2'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            modifyOutputPath: false
            zipAfterPublish: false
        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: 'app'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Free Trial(f4c13e81-6cbe-4949-ab59-f130a8a40d47)'
            appType: 'webApp'
            WebAppName: 'MyApp1111'
            packageForLinux: '$(Pipeline.Workspace)/app'