//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference1.IFridge")]
    public interface IFridge {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/HowMuchFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/HowMuchFruitResponse")]
        int HowMuchFruit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/HowMuchFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/HowMuchFruitResponse")]
        System.Threading.Tasks.Task<int> HowMuchFruitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/AddFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/AddFruitResponse")]
        int AddFruit(int amountToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/AddFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/AddFruitResponse")]
        System.Threading.Tasks.Task<int> AddFruitAsync(int amountToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/GetFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/GetFruitResponse")]
        int GetFruit(int amountToGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFridge/GetFruit", ReplyAction="http://Microsoft.ServiceModel.Samples/IFridge/GetFruitResponse")]
        System.Threading.Tasks.Task<int> GetFruitAsync(int amountToGet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFridgeChannel : GettingStartedClient.ServiceReference1.IFridge, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FridgeClient : System.ServiceModel.ClientBase<GettingStartedClient.ServiceReference1.IFridge>, GettingStartedClient.ServiceReference1.IFridge {
        
        public FridgeClient() {
        }
        
        public FridgeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FridgeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FridgeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FridgeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int HowMuchFruit() {
            return base.Channel.HowMuchFruit();
        }
        
        public System.Threading.Tasks.Task<int> HowMuchFruitAsync() {
            return base.Channel.HowMuchFruitAsync();
        }
        
        public int AddFruit(int amountToAdd) {
            return base.Channel.AddFruit(amountToAdd);
        }
        
        public System.Threading.Tasks.Task<int> AddFruitAsync(int amountToAdd) {
            return base.Channel.AddFruitAsync(amountToAdd);
        }
        
        public int GetFruit(int amountToGet) {
            return base.Channel.GetFruit(amountToGet);
        }
        
        public System.Threading.Tasks.Task<int> GetFruitAsync(int amountToGet) {
            return base.Channel.GetFruitAsync(amountToGet);
        }
    }
}
